# CAO_CRM (Corpus Author Ontology CRM)
# Copyright (c) 2026 Andres Echavarria Pelaez
# Consortium Huma-Num ARIANE -- AMIS project (Advanced Metadata Intelligent System)
# Encoding carried out under the scientific direction and support of Fatiha Idmhand
#
# This file is part of the CAO_CRM publication package, licensed under the
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
# License (CC BY-NC-SA 4.0). To view a copy of this license, visit
# https://creativecommons.org/licenses/by-nc-sa/4.0/
#

# CQ4 -- ¿Qué derechos aplican a esta edición digital, y quién los posee?
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dig: <http://www.cidoc-crm.org/extensions/crmdig/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?digitalObject ?right ?rightLabel WHERE {
  ?digitalObject a dig:D1_Digital_Object ;
                 crm:P104_is_subject_to ?right .
  OPTIONAL { ?right rdfs:label ?rightLabel }
}
