#!/usr/bin/env python3
#
# CAO_CRM (Corpus Author Ontology CRM)
# Copyright (c) 2026 Andres Echavarria Pelaez
# Consortium Huma-Num ARIANE -- AMIS project (Advanced Metadata Intelligent System)
# Encoding carried out under the scientific direction and support of Fatiha Idmhand
#
# This file is part of the CAO_CRM publication package, licensed under the
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
# License (CC BY-NC-SA 4.0). To view a copy of this license, visit
# https://creativecommons.org/licenses/by-nc-sa/4.0/
#
"""Compile translations*/*.yaml into a Turtle overlay of additional rdfs:label
and rdfs:comment literals, keyed by the same IRIs as the CAO_CRM module -- but
living entirely outside ontology/CAO_CRM-1.0.rdf.

The overlay is never merged into the published ontology file. It is only
merged into a temporary in-memory graph at documentation-build time, in
docs/build.sh.

Usage: python3 compile_i18n_overlay.py <translations-dir> <output.ttl> [lang [lang ...]]
       (langs default to fr es if omitted, for backward compatibility)
"""
import glob
import os
import sys

import rdflib
import yaml
from rdflib.namespace import RDFS

HEADER = """# CAO_CRM (Corpus Author Ontology CRM) -- documentation translation overlay
#
# THIS FILE IS NOT PART OF THE OFFICIAL CIDOC-CRM / LRMoo / CRMdig SOURCES.
# It supplies working labels/definitions, produced by the CAO_CRM team, for
# terms that the official standards only ever published in English (LRMoo,
# CRMdig) or that the official standards never translate at all (rdfs:comment
# / long definitions, in any language, for any of the three standards --
# confirmed empirically, see docs/i18n/README.md).
#
# This file is merged into a TEMPORARY, in-memory copy of the ontology only
# when generating the human-readable documentation (HTML/PDF). It is never
# merged into, or shipped alongside, ontology/CAO_CRM-1.0.rdf itself, which
# remains an exact, unmodified extraction from the official sources -- see
# the "pure composition" principle in docs/intro.html's Design Rationale.
#
# Generated by docs/i18n/scripts/compile_i18n_overlay.py -- do not edit by hand,
# edit the source YAML files in the corresponding translations*/ directory instead.

"""


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: compile_overlay.py <translations-dir> <output.ttl> [lang [lang ...]]")
    tdir, out_path = sys.argv[1], sys.argv[2]
    langs = sys.argv[3:] or ["fr", "es"]

    g = rdflib.Graph()
    count_labels = 0
    count_comments = 0
    seen_iris = set()

    for yml_path in sorted(glob.glob(os.path.join(tdir, "*.yaml"))):
        with open(yml_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
        for entry in data.get("terms", []):
            iri = entry["iri"]
            seen_iris.add(iri)
            subj = rdflib.URIRef(iri)
            for lang in langs:
                label = entry.get("label", {}).get(lang)
                if label:
                    g.add((subj, RDFS.label, rdflib.Literal(label, lang=lang)))
                    count_labels += 1
                comment = entry.get("comment", {}).get(lang)
                if comment:
                    g.add((subj, RDFS.comment, rdflib.Literal(comment, lang=lang)))
                    count_comments += 1

    ttl = g.serialize(format="turtle")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write(ttl)

    print(f"compile_overlay.py: {len(seen_iris)} terms, {count_labels} labels + {count_comments} comments -> {out_path} (langs: {', '.join(langs)})")


if __name__ == "__main__":
    main()
